name = "Minecraft Origins Modpack"
author = "DaddyNestea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ffaf73b040c5591711c126062006bc87187c6c4b6b9826c35c96c29948182e"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
