name = "Minecraft Origins Modpack"
author = "DaddyNestea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67b77515bea81061ff220accd16cc713013da38156a41768a620115313d06a02"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
