name = "Minecraft Origins Modpack"
author = "DaddyNestea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e2bdaf4e5c6eaace6cfbbd3481cc1d06ed06abd91ce07be1af5d10a3f3c6aa2"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
