name = "Minecraft Origins Modpack"
author = "DaddyNestea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a271a0a0078a6d31290d2a424ab341f7b317256990643c7048c59c37b5b091a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
