name = "Minecraft Origins Modpack"
author = "DaddyNestea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c521f1532128309708eb3f4ec081e3debbfd12f6cb48113cead9221c5ad4747"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
